"""Fixed test-harness support (copied verbatim into generated suites).

Hand-written and tested — NEVER generated by the LLM. Provides the base URL,
the Frill-popup dismiss, and a path navigation helper. Pairs with conftest.py.
"""
from __future__ import annotations

import os

BASE_URL = os.environ.get("BASE_URL", os.environ.get("TARGET_BASE_URL", "")).rstrip("/")

# Post-login success indicator (admin dashboard).
DASHBOARD_INDICATOR = "text=Add New Account"
LOGIN_EMAIL_LABEL = "Email Address"
LOGIN_PASSWORD_LABEL = "Password"
LOGIN_BUTTON = "#btn-login"
FRILL_MODAL = ".Frill_Notification_Modal"

# Where the app shell (with the sidebar) reliably loads after auth.
APP_START_PATH = "/members"

# Default Playwright timeouts (ms)
DEFAULT_TIMEOUT = 30_000
NAV_TIMEOUT = 30_000


def open_section(page, sidebar_selector: str) -> None:
    """Navigate to a section by clicking its sidebar entry (no URL guessing).

    Mirrors how the real framework navigates. Assumes the app shell (sidebar) is
    already loaded — the ``authenticated_page`` fixture ensures that.
    """
    page.locator(sidebar_selector).first.click(timeout=NAV_TIMEOUT)
    try:
        page.wait_for_load_state("domcontentloaded", timeout=NAV_TIMEOUT)
    except Exception:
        pass
    dismiss_frill(page)


def dismiss_frill(page) -> bool:
    """Remove the intermittent Frill 'what's new' popup if it appears.

    Waits up to 3s for it; if present, strips it from the DOM. Safe no-op when
    absent. The popup shows only sometimes, so this must always be conditional.
    """
    try:
        page.locator(FRILL_MODAL).wait_for(state="visible", timeout=3000)
    except Exception:
        return False
    try:
        page.evaluate(
            "() => { document.querySelectorAll('.Frill_Notification_Modal, .Frill_Notification')"
            ".forEach(el => el.remove()); }"
        )
        page.wait_for_timeout(300)
    except Exception:
        pass
    return True


def app_goto(page, path: str = "/") -> None:
    """Navigate to a path on the target app, then clear any Frill popup."""
    if not path.startswith("/"):
        path = "/" + path
    page.goto(f"{BASE_URL}{path}", wait_until="domcontentloaded", timeout=NAV_TIMEOUT)
    dismiss_frill(page)
