"""Fixed test-harness support (copied verbatim into generated suites).

Hand-written and tested — NEVER generated by the LLM. Provides the base URL,
the Frill-popup dismiss, and a path navigation helper. Pairs with conftest.py.
"""
from __future__ import annotations

import os

BASE_URL = os.environ.get("BASE_URL", os.environ.get("TARGET_BASE_URL", "")).rstrip("/")

# Post-login success indicator (admin dashboard).
DASHBOARD_INDICATOR = "text=Add New Account"
LOGIN_EMAIL_LABEL = "Email Address"
LOGIN_PASSWORD_LABEL = "Password"
LOGIN_BUTTON = "#btn-login"
FRILL_MODAL = ".Frill_Notification_Modal"

# Where the app shell (with the sidebar) reliably loads after auth.
APP_START_PATH = "/members"

# Default Playwright timeouts (ms)
DEFAULT_TIMEOUT = 30_000
NAV_TIMEOUT = 30_000


def open_section(page, sidebar_selector: str) -> None:
    """Navigate to a section by clicking its sidebar entry (no URL guessing).

    The sidebar starts collapsed (div.d-none). Clicking button.menu-button
    expands it. This checks visibility first so it only toggles when needed.
    """
    el = page.locator(sidebar_selector).first
    # Expand the sidebar if collapsed, then wait until the item is actually visible
    if not el.is_visible():
        try:
            page.locator("button.menu-button").click(timeout=5_000)
            el.wait_for(state="visible", timeout=8_000)
        except Exception:
            pass
    el.click(timeout=NAV_TIMEOUT)
    try:
        page.wait_for_load_state("domcontentloaded", timeout=NAV_TIMEOUT)
    except Exception:
        pass
    dismiss_frill(page)


def dismiss_frill(page) -> bool:
    """Dismiss any Frill popup/survey that could obscure the sidebar.

    Handles two flavours:
      1. The notification modal (DOM element) — removed via JS.
      2. The survey widget (rendered inside an iframe) — clicked via frame_locator.
    Safe no-op when neither is present.
    """
    dismissed = False

    # 1. Notification modal — try clicking its close button first so Frill
    #    records the dismissal in localStorage; fall back to JS removal.
    try:
        page.locator(FRILL_MODAL).wait_for(state="visible", timeout=3000)
        try:
            page.locator(f"{FRILL_MODAL} button[aria-label='Close'], {FRILL_MODAL} button.close").first.click(timeout=2000)
        except Exception:
            page.evaluate(
                "() => { document.querySelectorAll('.Frill_Notification_Modal, .Frill_Notification')"
                ".forEach(el => el.remove()); }"
            )
        page.wait_for_timeout(300)
        dismissed = True
    except Exception:
        pass

    # 2. Announcements popup (Frill sidebar iframe — aria-label="Close")
    try:
        ann_frame = page.frame_locator("[id^='Frill_Frame']:not([id^='Frill_Frame_survey'])")
        ann_frame.locator("button[aria-label='Close']").click(timeout=3000)
        page.wait_for_timeout(300)
        dismissed = True
    except Exception:
        pass

    # 3. Survey popup (inside iframe — id starts with "Frill_Frame_survey")
    try:
        survey_frame = page.frame_locator("[id^='Frill_Frame_survey']")
        survey_frame.locator("button[aria-label='Dismiss survey']").click(timeout=3000)
        page.wait_for_timeout(300)
        dismissed = True
    except Exception:
        pass

    return dismissed


def app_goto(page, path: str = "/") -> None:
    """Navigate to a path on the target app, then clear any Frill popup."""
    if not path.startswith("/"):
        path = "/" + path
    page.goto(f"{BASE_URL}{path}", wait_until="domcontentloaded", timeout=NAV_TIMEOUT)
    dismiss_frill(page)
